app = "meu-candidato-web"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  NEXT_PUBLIC_API_URL = "http://meu-candidato-api.internal:8000/api/v1"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  
  [[services.ports]]
    port = 80
  
  [[services.ports]]
    port = 443

[[services.http_checks]]
  path = "/"
  interval = "30s"
